# Generated by Django 5.1.6 on 2025-03-24 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_zlecenie_przewidywany_koszt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zlecenie',
            name='termin_realizacji',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Termin realizacji'),
        ),
    ]
