# Generated by Django 5.1.6 on 2025-04-04 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_zlecenie_termin_realizacji'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serwis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('opis', models.TextField()),
                ('koszt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ciezarowka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.ciezarowka')),
            ],
        ),
    ]
