# Generated by Django 5.1.6 on 2025-04-17 22:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_serwis'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciezarowka',
            name='ciez_bak_max',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Pojemność baku (l)'),
        ),
        migrations.AddField(
            model_name='ciezarowka',
            name='ciez_paliwo_litry',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stan paliwa (l)'),
        ),
    ]
