# Generated by Django 5.1.6 on 2025-04-17 22:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_ciezarowka_ciez_bak_max_ciezarowka_ciez_paliwo_litry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tankowanie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('ilosc_litrow', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('komentarz', models.TextField(blank=True, null=True)),
                ('ciezarowka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tankowania', to='users.ciezarowka')),
            ],
        ),
    ]
