# Generated by Django 5.1.6 on 2025-04-17 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_tankowanie'),
    ]

    operations = [
        migrations.AddField(
            model_name='tankowanie',
            name='cena_za_litr',
            field=models.DecimalField(decimal_places=2, default=6.26, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tankowanie',
            name='kierowca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.kierowca'),
        ),
        migrations.AddField(
            model_name='tankowanie',
            name='koszt',
            field=models.DecimalField(decimal_places=2, default=6.26, editable=False, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tankowanie',
            name='ciezarowka',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.ciezarowka'),
        ),
        migrations.AlterField(
            model_name='tankowanie',
            name='komentarz',
            field=models.TextField(blank=True, default=6.26),
            preserve_default=False,
        ),
    ]
