# Generated by Django 5.1.6 on 2025-04-18 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_tankowanie_cena_za_litr_tankowanie_kierowca_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tankowanie',
            name='koszt',
        ),
    ]
