# Generated by Django 5.1.6 on 2025-04-18 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_tankowanie_koszt'),
    ]

    operations = [
        migrations.AddField(
            model_name='tankowanie',
            name='koszt',
            field=models.DecimalField(decimal_places=2, default=6.26, editable=False, max_digits=10),
            preserve_default=False,
        ),
    ]
