# Generated by Django 5.1.6 on 2025-04-18 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_tankowanie_koszt'),
    ]

    operations = [
        migrations.AddField(
            model_name='tankowanie',
            name='zlecenie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.zlecenie'),
        ),
    ]
