# Generated by Django 5.1.6 on 2025-04-19 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_tankowanie_zlecenie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tankowanie',
            name='ilosc_litrow',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
