# Generated by Django 5.1.6 on 2025-06-01 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_tankowanie_ilosc_litrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='zlecenie',
            name='miejsce_wyj',
            field=models.CharField(default='Zakopiańska 20, Kraków', max_length=255, verbose_name='Miejsce wyjazdu'),
            preserve_default=False,
        ),
    ]
